!devrock.releasing.model.configuration.ReleaseConfiguration
  repositoryPrototype: !com.braintribe.devrock.model.repository.IndexedMavenHttpRepository
      name: "hiconic-os-release"

  includes:
    - "com.braintribe.common:*"
